apiVersion: v1
kind: Template
metadata:
  name: hs-hypershift-logging-operator-template
parameters:
  - name: REGISTRY_IMG
    required: true
  - name: IMAGE_DIGEST
    required: true
objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: hypershift-logging-operator-hs-policy
    spec:
      clusterDeploymentSelector:
        matchLabels:
          ext-hypershift.openshift.io/cluster-type: service-cluster
      resourceApplyMode: Sync
      resources:
        - apiVersion: apps.open-cluster-management.io/v1
          kind: PlacementRule
          metadata:
            name: hypershift-logging-operator
            namespace: openshift-acm-policies
          spec:
            clusterSelector:
              matchExpressions:
                - key: hypershift.open-cluster-management.io/management-cluster
                  operator: In
                  values:
                    - "true"
        - apiVersion: policy.open-cluster-management.io/v1
          kind: PlacementBinding
          metadata:
            name: hypershift-logging-operator
            namespace: openshift-acm-policies
          placementRef:
            name: hypershift-logging-operator
            kind: PlacementRule
            apiGroup: apps.open-cluster-management.io
          subjects:
            - name: hypershift-logging-operator
              kind: Policy
              apiGroup: policy.open-cluster-management.io
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          metadata:
            name: hypershift-logging-operator
            namespace: openshift-acm-policies
          spec:
            remediationAction: enforce
            disabled: false
            policy-templates:
              - objectDefinition:
                  apiVersion: policy.open-cluster-management.io/v1
                  kind: ConfigurationPolicy
                  metadata:
                    name: hypershift-logging-operator
                    annotations:
                      policy.open-cluster-management.io/disable-templates: "true"
                  spec:
                    namespaceSelector:
                      matchLabels:
                        hypershift.openshift.io/hosted-control-plane: "true"
                    pruneObjectBehavior: DeleteIfCreated
                    object-templates:
                      - complianceType: MustHave
                        objectDefinition:
                          apiVersion: package-operator.run/v1alpha1
                          kind: Package
                          metadata:
                            name: hypershift-logging-operator
                          spec:
                            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
