apiVersion: logging.managed.openshift.io/v1alpha1
kind: HyperShiftLogForwarder
metadata:
  name: http-to-cloudwatch-new
  namespace: openshift-logging
spec:
  inputs:
    - name: input-httpserver
      receiver:
        http:
          format: kubeAPIAudit
          receiverPort:
            name: httpserver
            port: 443
            targetPort: 8443
  outputs:
  - name: cloudwatch
    type: cloudwatch
    cloudwatch:
      groupPrefix:  sjayasin-hcp
      groupBy: logType
      region: us-east-2
    secret:
      name: cloudwatch-credentials
  pipelines:
  - inputRefs:
    - input-httpserver
    name: to-cloudwatch
    outputRefs:
    - cloudwatch
  serviceAccountName: clf-collector
